# This YAML defines a Deployment named "cloud-gateway-app" for deploying the "cloud-gateway-app" application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway-app  # Name of the Deployment
spec:
  selector:
    matchLabels:
      app: cloud-gateway-app  # Select pods with the label "app: cloud-gateway-app"
  template:
    metadata:
      labels:
        app: cloud-gateway-app  # Labels applied to pods created by this Deployment
    spec:
      containers:
        - name: cloud-gateway-app  # Name of the container
          image: abenezermulugeta/cloudgateway:0.0.1  # Docker image to run
          ports:
            - containerPort: 9090  # Port to expose on the container
          env:
            - name: EUREKA_SERVER_ADDRESS  # Environment variable for the container
              valueFrom:
                configMapKeyRef:
                  key: eureka_service_address  # Reference to a key in the "eureka-cm" ConfigMap
                  name: eureka-cm  # Name of the ConfigMap from which to fetch the key
            - name: CONFIG_SERVER_URL  # Another environment variable for the container
              valueFrom:
                configMapKeyRef:
                  key: config_service_url  # Reference to a key in the "config-cm" ConfigMap
                  name: config-cm  # Name of the ConfigMap from which to fetch the key

---

# This YAML defines a Service named "cloud-gateway-svc" for exposing the "cloud-gateway-app" application.
apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc  # Name of the Service
spec:
  type: LoadBalancer  # Specifies that a LoadBalancer should be used to provide external access
  selector:
    app: cloud-gateway-app  # Select pods with the label "app: cloud-gateway-app"
  ports:
  - port: 80  # Port exposed by the service externally
    targetPort: 9090  # Port on which the service is running within the container