# This YAML defines a ConfigMap named "eureka-cm" for storing configuration data.
apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm  # Name of the ConfigMap
data:
  # The structured URL "http://eureka-0.eureka:8761/eureka" appears to be pointing to the first pod (with ordinal number 0) in a headless StatefulSet named "eureka,"
  # specifically to the Eureka service running on port 8761 within that pod. This URL structure allows for direct communication with individual pods in the StatefulSet.
  eureka_service_address: "http://eureka-0.eureka:8761/eureka"  # Key-value pair stored in the ConfigMap

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm  # Name of the ConfigMap
data:
  # The structured URL "http://config-server-svc" appears to be pointing to the config server service (config-server-svc).
  config_service_url: "http://config-server-svc"  # Key-value pair stored in the ConfigMap