apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.0.4
        ports:
        - containerPort: 6379
        command:
          -  "redis-server"  # This command tells the pod to start as a server
        args:
          - "--protected-mode"
          - "no"

---

apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis-app
  ports:
  - port: 6379
    targetPort: 6379
