# Server configuration
server:
  port: 8081

spring:
  # Application configuration
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9296   # Client discovery configuration coming from config server in github
  # Database server configuration
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/paymentdb
    username: root
    password: 12345678@Az
    driverClassName: com.mysql.cj.jdbc.Driver
  # ORM library configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update