# server configuration
server:
  port: 9296

spring:
  # application configuration
  application:
    name: CONFIG-SEVER
  # config server configuration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abenezermulugeta9/store-management-microservice-config-server
          clone-on-start: true
