# Server configuration
server:
  port: 9090

spring:
  # Application configuration
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296 # Client discovery configuration coming from config server in github
  cloud:
    gateway: # Api gateway configuration
      routes:
        # Register a load-balanced order service in the api gateway
        - id : ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          # Configure circuit breaker for order service
          filters:
            - name : CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri: forward:/order-service-fallback # If the order service is down, the circuit breaker will forward the request to this api
        # Register a load-balanced product service in the api gateway
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
          # Configure circuit breaker for product service
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/product-service-fallback # If the product service is down, the circuit breaker will forward the request to this api
        # Register a load-balanced payment service in the api gateway
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
          # Configure circuit breaker for payment service
          filters:
            - name: CircuitBreaker
              args:
                name: PAYMENT-SERVICE
                fallbackuri: forward:/payment-service-fallback # If the payment service is down, the circuit breaker will forward the request to this api